use ctb3gejbzqwytitd;

DROP TABLE courses;
CREATE TABLE IF NOT EXISTS courses (
    `CourseId` INT,
    `courseName` VARCHAR(33) CHARACTER SET utf8,
    `courseCity` VARCHAR(16) CHARACTER SET utf8,
    `courseState` VARCHAR(14) CHARACTER SET utf8
);
INSERT INTO courses VALUES
    (1,'Highland Park','Birmingham','Alabama'),
    (2,'RTJ Oxmoor Valley','Birmingham','Alabama'),
    (3,'Roebuck Golf Course','Birmingham','Alabama'),
    (4,'Sunset Landing','Huntsville','Alabama'),
    (5,'Links At Redstone','Huntsville','Alabama'),
    (6,'Hampton Cove','Huntsville','Alabama'),
    (7,'Gateway','Montgomery','Alabama'),
    (8,'Lagoon Park','Montgomery','Alabama'),
    (9,'Aroostook','Montgomery','Alabama'),
    (10,'Anchorage ','Anchorage','Alaska'),
    (11,'Russian Jack Springs','Anchorage','Alaska'),
    (12,'Moose Run','Anchorage','Alaska'),
    (13,'Mendenhall ','Juneau','Alaska'),
    (14,'Disc Golf','Juneau','Alaska'),
    (15,'Aantiyeik','Juneau','Alaska'),
    (16,'North Star','Fairbanks','Alaska'),
    (17,'Fairbanks','Fairbanks','Alaska'),
    (18,'Chena Bend','Fairbanks','Alaska'),
    (19,'Raven Golf Club','Phoenix','Arizona'),
    (20,'Lookout Mountain','Phoenix','Arizona'),
    (21,'GCU Championship','Phoenix','Arizona'),
    (22,'El Rio ','Tucson','Arizona'),
    (23,'Randolph Dell Urich','Tucson','Arizona'),
    (24,'Silverbell','Tucson','Arizona'),
    (25,'Ocotillo','Chandler','Arizona'),
    (26,'Sunbird','Chandler','Arizona'),
    (27,'San Marcos','Chandler','Arizona'),
    (28,'Rebsamen Park','Little Rock','Arkansas '),
    (29,'Burns Park','Little Rock','Arkansas '),
    (30,'Eagle Hill','Little Rock','Arkansas '),
    (31,'Ben Green','Fort Smith','Arkansas '),
    (32,'Hardscrabble','Fort Smith','Arkansas '),
    (33,'Deer Trails','Fort Smith','Arkansas '),
    (34,'Stonebridge','Fayetteville','Arkansas '),
    (35,'Paradise Valley','Fayetteville','Arkansas '),
    (36,'Lakeside Village','Fayetteville','Arkansas '),
    (37,'Wilson & Harding','Los Angeles','California'),
    (38,'Rancho Park','Los Angeles','California'),
    (39,'Westchester','Los Angeles','California'),
    (40,'Balboa Park','San Diego','California'),
    (41,'Mission Bay ','San Diego','California'),
    (42,'Colina Park','San Diego','California'),
    (43,'Golden Gate Park','San Francisco','California'),
    (44,'Lincoln Park','San Francisco','California'),
    (45,'Gleneagles at McLaren','San Francisco','California'),
    (46,'Wellshire','Denver','Colorado'),
    (47,'Willis Case','Denver','Colorado'),
    (48,'Foothills','Denver','Colorado'),
    (49,'World Golf & Sand Creek','Colorado Springs','Colorado'),
    (50,'Cherokee Ridge','Colorado Springs','Colorado'),
    (51,'Patty Jewett','Colorado Springs','Colorado'),
    (52,'Collindale','Fort Collins','Colorado'),
    (53,'City Park Nine','Fort Collins','Colorado'),
    (54,'Southridge','Fort Collins','Colorado'),
    (55,'Fairchild Wheeler','Bridgeport','Connecticut'),
    (56,'Short Beach','Bridgeport','Connecticut'),
    (57,'Tashua Knolls & Tashua Glen','Bridgeport','Connecticut'),
    (58,'Yale','New Haven','Connecticut'),
    (59,'Alling Memorial','New Haven','Connecticut'),
    (60,'Knickerbocker','New Haven','Connecticut'),
    (61,'Sterling Farms','Stamford','Connecticut'),
    (62,'E Gaynor Brennan','Stamford','Connecticut'),
    (63,'Innis Arden','Stamford','Connecticut'),
    (64,'Rock Manor','Wilmington','Delaware'),
    (65,'Dupont ','Wilmington','Delaware'),
    (66,'Ed Oliver','Wilmington','Delaware'),
    (67,'Eagle Creek','Dover','Delaware'),
    (68,'Jonathans Landing','Dover','Delaware'),
    (69,'Maple Dale','Dover','Delaware'),
    (70,'Deerfield','Newark','Delaware'),
    (71,'Newark','Newark','Delaware'),
    (72,'White Clay Creek','Newark','Delaware'),
    (73,'Langston','Washington','DC'),
    (74,'East Potomac','Washington','DC'),
    (75,'Rock Creek Park','Washington','DC'),
    (76,'Eagle Harbor','Jacksonville','Florida'),
    (77,'Deerwood','Jacksonville','Florida'),
    (78,'Windsor Parke','Jacksonville','Florida'),
    (79,'Crandon Golf at Key Biscayne','Miami','Florida'),
    (80,'Miami Shores','Miami','Florida'),
    (81,'Biltmore','Miami','Florida'),
    (82,'Pebble Creek','Tampa','Florida'),
    (83,'Rocky Point','Tampa','Florida'),
    (84,'Babe Zaharias','Tampa','Florida'),
    (85,'Candler Park','Atlanta','Georgia'),
    (86,'North Fulton','Atlanta','Georgia'),
    (87,'John A White','Atlanta','Georgia'),
    (88,'Augusta Municipal','Augusta','Georgia'),
    (89,'Forest Hills','Augusta','Georgia'),
    (90,'The River','Augusta','Georgia'),
    (91,'Godwin Creek','Columbus','Georgia'),
    (92,'Maple Ridge','Columbus','Georgia'),
    (93,'Fort Benning','Columbus','Georgia'),
    (94,'Ala Wai','Honolulu','Hawaii'),
    (95,'Hawaii Kai','Honolulu','Hawaii'),
    (96,'Hawaii Tee','Honolulu','Hawaii'),
    (97,'Pearl ','Pearl City','Hawaii'),
    (98,'Hawaii State','Pearl City','Hawaii'),
    (99,'Waikele ','Pearl City','Hawaii'),
    (100,'Royal Hawaiian ','Kailua','Hawaii'),
    (101,'Pali','Kailua','Hawaii'),
    (102,'Mid Pacific','Kailua','Hawaii'),
    (103,'Warm Springs','Boise','Idaho'),
    (104,'Indian Lakes','Boise','Idaho'),
    (105,'Quail Hollow','Boise','Idaho'),
    (106,'Lakeview','Meridian','Idaho'),
    (107,'BanBury','Meridian','Idaho'),
    (108,'Indian Lakes','Meridian','Idaho'),
    (109,'Sage Lakes','Idaho Falls','Idaho'),
    (110,'Pinecrest','Idaho Falls','Idaho'),
    (111,'Sand Creek','Idaho Falls','Idaho'),
    (112,'Columbus Park','Chicago','Illinois'),
    (113,'Jackson Park','Chicago','Illinois'),
    (114,'Billy Caldwell','Chicago','Illinois'),
    (115,'Phillips Park','Aurora','Illinois'),
    (116,'Orchard Valley','Aurora','Illinois'),
    (117,'Aurora','Aurora','Illinois'),
    (118,'Springbrook','Naperville','Illinois'),
    (119,'Tamarack','Naperville','Illinois'),
    (120,'Naperbrook','Naperville','Illinois'),
    (121,'The Fort','Indianapolis','Indiana'),
    (122,'Buffer Park','Indianapolis','Indiana'),
    (123,'Coffin','Indianapolis','Indiana'),
    (124,'Donald Ross','Fort Wayne','Indiana'),
    (125,'Riverbend','Fort Wayne','Indiana'),
    (126,'Brookwood','Fort Wayne','Indiana'),
    (127,'McDonald','Evansville','Indiana'),
    (128,'Thunderbolt Pass','Evansville','Indiana'),
    (129,'Fendrich','Evansville','Indiana'),
    (130,'Waveland','Des Moines','Iowa'),
    (131,'AH Bank','Des Moines','Iowa'),
    (132,'Willow Creek','Des Moines','Iowa'),
    (133,'Ellis','Cedar Rapids','Iowa'),
    (134,'Twin Pines','Cedar Rapids','Iowa'),
    (135,'Cedar Rapids','Cedar Rapids','Iowa'),
    (136,'Emeis','Davenport','Iowa'),
    (137,'Duck Creek','Davenport','Iowa'),
    (138,'Red Hawk','Davenport','Iowa'),
    (139,'Auburn Hills','Wichita','Kansas'),
    (140,'Pine Pay','Wichita','Kansas'),
    (141,'Arthur B Sim','Wichita','Kansas'),
    (142,'Sykes Lady Overland Park','Overland Park','Kansas'),
    (143,'St Andrews','Overland Park','Kansas'),
    (144,'Deer Creek','Overland Park','Kansas'),
    (145,'Painted Hills','Kansas City','Kansas'),
    (146,'Dubs Dread','Kansas City','Kansas'),
    (147,'Sunflower Hills','Kansas City','Kansas'),
    (148,'Crescent Hill','Louisville','Kentucky'),
    (149,'Seneca','Louisville','Kentucky'),
    (150,'Iroquois','Louisville','Kentucky'),
    (151,'Tates Creek','Lexington','Kentucky'),
    (152,'Lakeside ','Lexington','Kentucky'),
    (153,'Gary Brewer Jr','Lexington','Kentucky'),
    (154,'Cross Winds','Bowling Green','Kentucky'),
    (155,'Riverview','Bowling Green','Kentucky'),
    (156,'Paul Walker','Bowling Green','Kentucky'),
    (157,'Audubon Park','New Orleans','Louisiana'),
    (158,'Joseph M Bartholomew','New Orleans','Louisiana'),
    (159,'Bayou Oaks','New Orleans','Louisiana'),
    (160,'LSU ','Baton Rouge ','Louisiana'),
    (161,'Santa Maria','Baton Rouge ','Louisiana'),
    (162,'City Park','Baton Rouge ','Louisiana'),
    (163,'Querbes Park','Shreveport','Louisiana'),
    (164,'Jerry Brooks','Shreveport','Louisiana'),
    (165,'The Club at Huntington Park','Shreveport','Louisiana'),
    (166,'City South Portland','Portland','Maine'),
    (167,'Riverside','Portland','Maine'),
    (168,'Nonesuch River','Portland','Maine'),
    (169,'Apple Valley','Lewiston','Maine'),
    (170,'Fox Ridge','Lewiston','Maine'),
    (171,'Pine Acres','Lewiston','Maine'),
    (172,'Bangor Municipal','Bangor','Maine'),
    (173,'Hermon Meadow','Bangor','Maine'),
    (174,'Bangor ','Bangor','Maine'),
    (175,'Clifton Park','Baltimore','Maryland'),
    (176,'Carroll Park','Baltimore','Maryland'),
    (177,'Forest Park','Baltimore','Maryland'),
    (178,'Clustered Spires','Frederick','Maryland'),
    (179,'Whiskey Creek','Frederick','Maryland'),
    (180,'Worthington Manor','Frederick','Maryland'),
    (181,'MCG','Rockville','Maryland'),
    (182,'Needwood','Rockville','Maryland'),
    (183,'Falls Road','Rockville','Maryland'),
    (184,'Newton Commonwealth','Boston','Massachusetts'),
    (185,'Robert T Lynch','Boston','Massachusetts'),
    (186,'William J Devine','Boston','Massachusetts'),
    (187,'Green Hill','Worcester','Massachusetts'),
    (188,'Pakachoag','Worcester','Massachusetts'),
    (189,'Wachusett','Worcester','Massachusetts'),
    (190,'Veterans Memorial','Springfield','Massachusetts'),
    (191,'Franconia','Springfield','Massachusetts'),
    (192,'Springfield','Springfield','Massachusetts'),
    (193,'Chandler Park','Detroit','Michigan'),
    (194,'Rouge Park','Detroit','Michigan'),
    (195,'Glenhurt','Detroit','Michigan'),
    (196,'Indian Trails','Grand Rapids','Michigan'),
    (197,'Mines','Grand Rapids','Michigan'),
    (198,'Lincoln','Grand Rapids','Michigan'),
    (199,'Huron Hills','Ann Arbor','Michigan'),
    (200,'Leslie Park','Ann Arbor','Michigan'),
    (201,'University of Michigan','Ann Arbor','Michigan'),
    (202,'Hiawatha','Minneapolis','Minnesota'),
    (203,'Theodore Wirth','Minneapolis','Minnesota'),
    (204,'Fort Snelling','Minneapolis','Minnesota'),
    (205,'Como Park','Saint Paul','Minnesota'),
    (206,'Highland National','Saint Paul','Minnesota'),
    (207,'Phalen Park','Saint Paul','Minnesota'),
    (208,'Northern Hills','Rochester','Minnesota'),
    (209,'Eastwood','Rochester','Minnesota'),
    (210,'Hadley Creek','Rochester','Minnesota'),
    (211,'Grove Park','Jackson','Mississippi'),
    (212,'Pearl Municipal','Jackson','Mississippi'),
    (213,'Pete Brown','Jackson','Mississippi'),
    (214,'Bayou Vista','Gulfport','Mississippi'),
    (215,'Great Southern','Gulfport','Mississippi'),
    (216,'Grand Bear','Gulfport','Mississippi'),
    (217,'Southaven','Southaven','Mississippi'),
    (218,'North Creek','Southaven','Mississippi'),
    (219,'Whitehaven','Southaven','Mississippi'),
    (220,'Royal Meadows','Kansas City','Missouri'),
    (221,'Heart of America','Kansas City','Missouri'),
    (222,'Swope Memorial','Kansas City','Missouri'),
    (223,'Forest Park ','Saint Louis','Missouri'),
    (224,'The Highlands','Saint Louis','Missouri'),
    (225,'Ruth Park','Saint Louis','Missouri'),
    (226,'Bill & Payne Stewart','Springfield','Missouri'),
    (227,'Horton Smith','Springfield','Missouri'),
    (228,'Springfield','Springfield','Missouri'),
    (229,'Lake Hills','Billings','Montana'),
    (230,'Exchange City','Billings','Montana'),
    (231,'Briarwood','Billings','Montana'),
    (232,'Linda Vista','Missoula','Montana'),
    (233,'Larchmont','Missoula','Montana'),
    (234,'University of Montana','Missoula','Montana'),
    (235,'Bridger Creek','Bozeman','Montana'),
    (236,'Valley View','Bozeman','Montana'),
    (237,'Cottonwood Hills','Bozeman','Montana'),
    (238,'Elmwood','Omaha','Nebraska'),
    (239,'Benson Championship','Omaha','Nebraska'),
    (240,'Johnny Goodman','Omaha','Nebraska'),
    (241,'Mahoney','Lincoln','Nebraska'),
    (242,'Pioneers','Lincoln','Nebraska'),
    (243,'Highlands','Lincoln','Nebraska'),
    (244,'Tregaron','Bellevue','Nebraska'),
    (245,'Willow Lakes','Bellevue','Nebraska'),
    (246,'Fontenelle','Bellevue','Nebraska'),
    (247,'Las Vegas','Las Vegas','Nevada'),
    (248,'Desert Pines','Las Vegas','Nevada'),
    (249,'Highland Falls','Las Vegas','Nevada'),
    (250,'The Revere','Henderson','Nevada');
    
INSERT INTO courses VALUES
    (251,'Desert Willow','Henderson','Nevada'),
    (252,'Wildhorse','Henderson','Nevada'),
    (253,'Sierra Sage','Reno','Nevada'),
    (254,'Washoe','Reno','Nevada'),
    (255,'Wildcreek','Reno','Nevada'),
    (256,'Derryfield','Manchester','New Hampshire'),
    (257,'Manchester ','Manchester','New Hampshire'),
    (258,'Intervale','Manchester','New Hampshire'),
    (259,'Beaver Meadow','Concord','New Hampshire'),
    (260,'Canterbury Woods','Concord','New Hampshire'),
    (261,'Loudon','Concord','New Hampshire'),
    (262,'Cochecho','Dover','New Hampshire'),
    (263,'The Oaks','Dover','New Hampshire'),
    (264,'Bellamy Park','Dover','New Hampshire'),
    (265,'Weequahic Park','Newark','New Jersey'),
    (266,'Liberty National','Newark','New Jersey'),
    (267,'Skyway at Lincoln Park West','Newark','New Jersey'),
    (268,'Francis A Byrne','Jersey City','New Jersey'),
    (269,'Hendricks Field','Jersey City','New Jersey'),
    (270,'Skyway','Jersey City','New Jersey'),
    (271,'Galloping Hill','Elizabeth','New Jersey'),
    (272,'Suburban','Elizabeth','New Jersey'),
    (273,'Spooky Brook','Elizabeth','New Jersey'),
    (274,'Los Altos','Albuquerque','New Mexico'),
    (275,'University of New Mexico','Albuquerque','New Mexico'),
    (276,'Arroyo Del Oso','Albuquerque','New Mexico'),
    (277,'NMSU','Las Cruces','New Mexico'),
    (278,'Sonoma Ranch','Las Cruces','New Mexico'),
    (279,'Red Hawk','Las Cruces','New Mexico'),
    (280,'Quail Run','Santa Fe','New Mexico'),
    (281,'Santa Fe','Santa Fe','New Mexico'),
    (282,'Marty Sanchez Links','Santa Fe','New Mexico'),
    (283,'Marine Park','New York City','New York'),
    (284,'Pelham Bay and Split Rock','New York City','New York'),
    (285,'Forest Park','New York City','New York'),
    (286,'Cazenovia Park','Buffalo','New York'),
    (287,'Grover Cleveland','Buffalo','New York'),
    (288,'Delaware Park','Buffalo','New York'),
    (289,'Genesee Valley','Rochester','New York'),
    (290,'Durand Eastman','Rochester','New York'),
    (291,'Lake Shore','Rochester','New York'),
    (292,'Sunset Hills','Charlotte','North Carolina'),
    (293,'Dr Charles L Sifford','Charlotte','North Carolina'),
    (294,'Harry L Jones Sr','Charlotte','North Carolina'),
    (295,'Lonnie Poole','Raleigh','North Carolina'),
    (296,'Raleigh Golf Association','Raleigh','North Carolina'),
    (297,'WilMar Golf Club','Raleigh','North Carolina'),
    (298,'Grandover','Greensboro','North Carolina'),
    (299,'Gillespie','Greensboro','North Carolina'),
    (300,'Crooked Tree','Greensboro','North Carolina'),
    (301,'Rose Creek','Fargo','North Dakota'),
    (302,'Edgewood Golf','Fargo','North Dakota'),
    (303,'Prairiewood','Fargo','North Dakota'),
    (304,'Tom OLeary','Bismarck','North Dakota'),
    (305,'Pebble Creek','Bismarck','North Dakota'),
    (306,'Riverwood','Bismarck','North Dakota'),
    (307,'Kings Walk','Grand Forks','North Dakota'),
    (308,'Lincoln','Grand Forks','North Dakota'),
    (309,'Valley ','Grand Forks','North Dakota'),
    (310,'Gahanna','Columbus','Ohio'),
    (311,'Champions','Columbus','Ohio'),
    (312,'Raymond Memorial','Columbus','Ohio'),
    (313,'Little Met','Cleveland','Ohio'),
    (314,'Ridgewood','Cleveland','Ohio'),
    (315,'Mastick','Cleveland','Ohio'),
    (316,'Avon Fields','Cincinnati','Ohio'),
    (317,'Woodland Golf','Cincinnati','Ohio'),
    (318,'California','Cincinnati','Ohio'),
    (319,'Lake Hefner','Oklahoma City','Oklahoma'),
    (320,'Earlywine','Oklahoma City','Oklahoma'),
    (321,'Trosper','Oklahoma City','Oklahoma'),
    (322,'Mohawk Park','Tulsa','Oklahoma'),
    (323,'Page Belcher','Tulsa','Oklahoma'),
    (324,'Battle Creek','Tulsa','Oklahoma'),
    (325,'Westwood Park','Norman','Oklahoma'),
    (326,'Cobblestone','Norman','Oklahoma'),
    (327,'The Trails','Norman','Oklahoma'),
    (328,'Eastmoreland','Portland','Oregon'),
    (329,'Rose City','Portland','Oregon'),
    (330,'Colwood','Portland','Oregon'),
    (331,'Meadowlawn','Salem','Oregon'),
    (332,'Salem','Salem','Oregon'),
    (333,'Creekside','Salem','Oregon'),
    (334,'RiverRidge','Eugene','Oregon'),
    (335,'Laurelwood','Eugene','Oregon'),
    (336,'Oakway','Eugene','Oregon'),
    (337,'Walnut Lane','Philadelphia','Pennsylvania'),
    (338,'Karakung','Philadelphia','Pennsylvania'),
    (339,'Bala','Philadelphia','Pennsylvania'),
    (340,'Mt Lebanon','Pittsburgh','Pennsylvania'),
    (341,'Bob OConnor','Pittsburgh','Pennsylvania'),
    (342,'South Park','Pittsburgh','Pennsylvania'),
    (343,'Allentown Municipal','Allentown','Pennsylvania'),
    (344,'Shepherd Hills','Allentown','Pennsylvania'),
    (345,'Wedgewood','Allentown','Pennsylvania'),
    (346,'Triggs Memorial','Providence','Rhode Island'),
    (347,'Metacomet','Providence','Rhode Island'),
    (348,'Louisquisset','Providence','Rhode Island'),
    (349,'Cranston','Cranston','Rhode Island'),
    (350,'Midville','Cranston','Rhode Island'),
    (351,'Triggs Memorial','Cranston','Rhode Island'),
    (352,'Midville','Warwick','Rhode Island'),
    (353,'Potowomut','Warwick','Rhode Island'),
    (354,'North Kingston','Warwick','Rhode Island'),
    (355,'City of Charleston','Charleston','South Carolina'),
    (356,'Shadowmoss','Charleston','South Carolina'),
    (357,'Charleston Golf','Charleston','South Carolina'),
    (358,'Fort Jackson','Columbia','South Carolina'),
    (359,'The Woodlands','Columbia','South Carolina'),
    (360,'Linrick','Columbia','South Carolina'),
    (361,'Charleston National','Mount Pleasant','South Carolina'),
    (362,'Patriots Points Links','Mount Pleasant','South Carolina'),
    (363,'Dunes West','Mount Pleasant','South Carolina'),
    (364,'Prairie Green','Sioux Falls','South Dakota'),
    (365,'Elmwood Golf','Sioux Falls','South Dakota'),
    (366,'Kuehn Park','Sioux Falls','South Dakota'),
    (367,'Meadowbrook','Rapid City','South Dakota'),
    (368,'Red Rock','Rapid City','South Dakota'),
    (369,'Hart Ranch','Rapid City','South Dakota'),
    (370,'Lee Parks','Aberdeen','South Dakota'),
    (371,'Rolling Hills','Aberdeen','South Dakota'),
    (372,'Moccasin Creek','Aberdeen','South Dakota'),
    (373,'Ted Rhodes','Nashville','Tennessee'),
    (374,'McCabe','Nashville','Tennessee'),
    (375,'Shelby','Nashville','Tennessee'),
    (376,'The Links at Overton Park','Memphis','Tennessee'),
    (377,'The Links at Pine Hill','Memphis','Tennessee'),
    (378,'The Links at Riverside','Memphis','Tennessee'),
    (379,'Knoxville Municipal','Knoxville','Tennessee'),
    (380,'Williams Creek','Knoxville','Tennessee'),
    (381,'Concord Park','Knoxville','Tennessee'),
    (382,'Memorial Park','Houston ','Texas'),
    (383,'Pasadena Municipal','Houston ','Texas'),
    (384,'Tour 18','Houston ','Texas'),
    (385,'Lions Municipal','Austin','Texas'),
    (386,'Morris Williams','Austin','Texas'),
    (387,'Roy Kizer','Austin','Texas'),
    (388,'Tenison Park','Dallas','Texas'),
    (389,'Stevens Park','Dallas','Texas'),
    (390,'Cedar Crest','Dallas','Texas'),
    (391,'Nibley Park','Salt Lake City','Utah'),
    (392,'Glendale','Salt Lake City','Utah'),
    (393,'Rose Park','Salt Lake City','Utah'),
    (394,'The Ridge','West Valley City','Utah'),
    (395,'Stonebridge','West Valley City','Utah'),
    (396,'Glendale','West Valley City','Utah'),
    (397,'Timpanogos','Provo','Utah'),
    (398,'Hobble Creek','Provo','Utah'),
    (399,'The Oaks at Spanish Fork','Provo','Utah'),
    (400,'Burlington','Burlington','Vermont'),
    (401,'Kwiniaska','Burlington','Vermont'),
    (402,'The Links at Lang Farm','Burlington','Vermont'),
    (403,'Stonehedge','Rutland','Vermont'),
    (404,'Baxters Rutland','Rutland','Vermont'),
    (405,'Killington','Rutland','Vermont'),
    (406,'Montpelier Elks','Montpelier','Vermont'),
    (407,'Country Club of Barre','Montpelier','Vermont'),
    (408,'Country Club of Vermont','Montpelier','Vermont'),
    (409,'Virginia Beach National','Virginia Beach','Virginia'),
    (410,'Red Wing Lake','Virginia Beach','Virginia'),
    (411,'Bow Creek','Virginia Beach','Virginia'),
    (412,'Sewells Point','Norfolk','Virginia'),
    (413,'Ocean View','Norfolk','Virginia'),
    (414,'Lamberts Point','Norfolk','Virginia'),
    (415,'Glenwood','Richmond','Virginia'),
    (416,'The First Tee of Greater Richmond','Richmond','Virginia'),
    (417,'Belmont','Richmond','Virginia'),
    (418,'West Seattle','Seattle','Washington'),
    (419,'Jackson Park','Seattle','Washington'),
    (420,'Jefferson Park','Seattle','Washington'),
    (421,'Indian Canyon','Spokane','Washington'),
    (422,'Downriver','Spokane','Washington'),
    (423,'Creek at Qualchan','Spokane','Washington'),
    (424,'North Shore Public','Tacoma','Washington'),
    (425,'Meadow Park','Tacoma','Washington'),
    (426,'Allenmore','Tacoma','Washington'),
    (427,'Little Creek','Charleston','West Virginia'),
    (428,'Cato Park','Charleston','West Virginia'),
    (429,'Berry Hills','Charleston','West Virginia'),
    (430,'Guyan','Huntington','West Virginia'),
    (431,'Sugarwood','Huntington','West Virginia'),
    (432,'Esquire','Huntington','West Virginia'),
    (433,'The Pines','Morgantown','West Virginia'),
    (434,'Mountaineer','Morgantown','West Virginia'),
    (435,'Pikewood National','Morgantown','West Virginia'),
    (436,'Lake Park','Milwaukee','Wisconsin '),
    (437,'Dretzka Park','Milwaukee','Wisconsin '),
    (438,'Doyne Park','Milwaukee','Wisconsin '),
    (439,'Glenway','Madison','Wisconsin '),
    (440,'Odana Hills','Madison','Wisconsin '),
    (441,'Yahara Hills','Madison','Wisconsin '),
    (442,'Village Green','Green Bay','Wisconsin '),
    (443,'Shorewood','Green Bay','Wisconsin '),
    (444,'Woods','Green Bay','Wisconsin '),
    (445,'Prairie View','Cheyenne','Wyoming'),
    (446,'Airport','Cheyenne','Wyoming'),
    (447,'Little America','Cheyenne','Wyoming'),
    (448,'Casper Municipal','Casper','Wyoming'),
    (449,'Three Crowns','Casper','Wyoming'),
    (451,'Jacoby','Laramie','Wyoming'),
    (452,'Fox Run','Laramie','Wyoming'),
    (453,'Spring Creek','Laramie','Wyoming');
